version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: taskflow-redis
    ports:
      - "6379:6379"
    networks:
      - taskflow_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskflow-backend
    ports:
      - "5000:5000"
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
      QUEUE_NAME: ${QUEUE_NAME}
      NODE_ENV: ${NODE_ENV}
      CLIENT_URL: ${CLIENT_URL}
    depends_on:
      - redis
    networks:
      - taskflow_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: taskflow-worker
    environment:
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      NODE_ENV: ${NODE_ENV}
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      - redis
    networks:
      - taskflow_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskflow-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - taskflow_network

  mongodb:
    image: mongo:latest
    container_name: taskflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - taskflow_network

networks:
  taskflow_network:
    driver: bridge

volumes:
  mongo_data: